import = [
    "~/.config/alacritty/themes/coolnight.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
# opacity = 0.5

decorations = "Buttonless"

[font]
normal.family = "MesloLGS NF"
bold.family = "MesloLGS NF"
italic.family = "MesloLGS NF"
bold_italic.family = "MesloLGS NF"

# normal.family = "JetBrainsMono Nerd Font"
# bold.family = "JetBrainsMono Nerd Font"
# italic.family = "JetBrainsMono Nerd Font"
# bold_italic.family = "JetBrainsMono Nerd Font"


#regular
size = 11

#for video
# size = 35.0
