# Default colors
[colors.primary]
background = '#011423'
foreground = '#CBE0F0'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = "#011423"
cursor = "#479CBB"

[colors.normal]
black = '0x100e23'
red = '0xff5458'
green = '0x62d196'
yellow = '0xffb378'
blue = '0x65b2ff'
magenta = '0x906cff'
cyan = '0x63f2f1'
white = '0xcbe3e7'

[colors.bright]
black = '0x565575'
red = '0xff8080'
green = '0x95ffa4'
yellow = '0xffe9aa'
blue = '0x91ddff'
magenta = '0xc991e1'
cyan = '0xaaffe4'
white = '0xe8fafc'
